config/routes.rb
Rails.application.routes.draw do
  root "welcome#show"
  get "/auth/github", as: :github_login
  get "/auth/github/callback", to: "sessions#create"

  get "/user/repos", to: "repos#index", as: :repos
  get "/user/organizations", to: "organizations#index", as: :organizations
  get "/user/events", to: "events#index", as: :events
  get "/user/gists", to: "gists#index", as: :gists
  resources :events, only: [:show]

  delete "/logout", to: "sessions#destroy", as: :logout
end

app/models/event.rb
class Event
  attr_reader :service

  def initialize(user)
    @service ||= GithubServices.new(user)
  end

  def type_change(type)
    types = {"CreateEvent" => "created",
             "WatchEvent"  => "starred",
             "ForkEvent"   => "forked",
             "MemberEvent" => "added a collaborator to" }
    new_type = types[type]
  end

  def all
    temp_events_array = service.events_array
    temp_events_array.map do |event|
      {name: event[:actor][:login], type: type_change(event[:type]), repo_name: event[:repo][:name]}
    end
  end

  def my_all
    events = service.my_events_array
    all = events.map do |event|
      {repo: event[:repo][:name], url: event[:repo][:url], other: event}
    end
  end


end

app/models/gist.rb
class Gist
  attr_reader :service

  def initialize(user)
    @service ||= GithubServices.new(user)
  end

  def all
    gists_array = service.gists_hash
    file_name = gists_array.map do |agist|
      {name: agist[:files].values.first[:filename], link: agist[:files].values.first[:raw_url]}
    end
  end
end

app/models/github_information.rb
class GithubInformation

  attr_accessor :id, :screen_name, :uid, :created_at, :updated_at, :name

  def initialize(user_hash)
    @id = user_hash[:id]
    @screen_name = user_hash[:screen_name]
    @uid = user_hash[:uid]
    @created_at = user_hash[:created_at]
    @updated_at = user_hash[:updated_at]
    @name = user_hash[:name]
  end

 def self.find_image
    user_array = GithubServices.new.user_hash(get_image)
    user_array.image
 end

 def self.find_starred
    user_array = GithubServices.new.star_hash
    user_array.starred_url
 end

 def self.find_repos
    temp_repo_hash = GithubServices.new.repo_hash
 end

end

app/models/organization.rb
class Organization
  attr_reader :service

  def initialize(user)
    @service ||= GithubServices.new(user)
  end

  def all
      orgs = service.orgs_array.map do |org|
        {name: org[:login], link: org[:url] }
      end
  end

end

app/models/repo.rb
class Repo
  attr_reader :service

  def initialize(user)
    @service ||= GithubServices.new(user)
  end

  def all
    repo_array = service.repo_hash
    repo_array.map do |repo|
      {name: repo[:name], link: repo[:html_url]}
    end
  end

  def starred
    starred_repo_array = service.star_hash
    starred_repo_array.map {|repo| repo[:name]}
  end



end

app/models/user.rb
class User < ActiveRecord::Base

  def self.from_omniauth(auth_info)
    new_user = where(uid: auth_info[:uid]).first_or_create
    new_user.followers = auth_info.extra.raw_info.followers
    new_user.following = auth_info.extra.raw_info.following
    new_user.image = auth_info.extra.raw_info.avatar_url
    new_user.uid = auth_info.uid
    new_user.name = auth_info.extra.raw_info.name
    new_user.screen_name = auth_info.info.nickname
    new_user.oauth_token = auth_info.credentials.token
    new_user.save
    return new_user
  end




end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    event = Event.new(current_user)
    @events = event.all
  end

  def show
    event = Event.new(current_user)
    @my_events = event.my_all
  end
end

app/controllers/gists_controller.rb
class GistsController < ApplicationController
  def index
    gist = Gist.new(current_user)
    @gists = gist.all
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  def index
    org = Organization.new(current_user)
    @orgs = org.all
  end
end

app/controllers/repos_controller.rb
class ReposController < ApplicationController

  def index
    repo = Repo.new(current_user)
    @repos = repo.all
  end



end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    if user = User.from_omniauth(request.env["omniauth.auth"])
      session[:user_id] = user.id
    end
    redirect_to root_path
  end

  def destroy
    session.clear
    redirect_to root_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def show
    if current_user
      repo = Repo.new(current_user)
      @starred = repo.starred
      organization = Organization.new(current_user)
      @organizations = organization.all
      event = Event.new(current_user)
      @my_events = event.my_all
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/events/index.html.erb
<div class="container">
  <h2>What Your Friends Are Up To</h2>
  <% @events.each do |event| %>
    <p><%= event[:name] %> <%= event[:type] %> <%= event[:repo_name] %></p>
  <% end %>
</div>

app/views/events/show.html.erb
<div class="container">
  <h2>Your Recent Activity</h2>
  <% @my_events.each do |event| %>
    <p>You contributed to <%= link_to event[:repo], event[:url] %></p>
  <% end %>
</div>

app/views/gists/index.html.erb
<div class="container">
  <h2>All Your Gists</h2>
  <h4> Click link for a raw version of your gist</h4>
  <br>
  <% @gists.each do |agist| %>
    <p><%= link_to agist[:name], agist[:link] %></p>
  <% end %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">

    <div class="navbar-header">
      <a class="navbar-brand" href="/">MyGitPlace</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right nav-pills">
        <% if current_user %>
          Hello, <%= current_user.name %>
          <%= link_to "Logout", logout_path, method: :delete %>
        <% else %>
          <%= link_to "Sign in with Github", github_login_path %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyGitPlace</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <link href='https://fonts.googleapis.com/css?family=Ubuntu:700'rel='stylesheet' type='text/css'>
     <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render "layouts/navbar" %>

    <% flash.each do |type, message| %>
      <h5><%= content_tag :div, message.html_safe, class:"flash-#{type}" %></h5>
    <% end %>
    <%= yield %>

  </body>
</html>

app/views/organizations/index.html.erb
<div class="container">
  <h1>All Organizations</h1>
  <% @orgs.each do |org| %>
    <p><%=org[:name] %></p>
  <% end %>
</div>

app/views/repos/index.html.erb
<div class ="container">
  <p>All The Repos</p>
  <div class= "repos-index">
    <% @repos.each do |repo| %>
      <p><%= link_to repo[:name], repo[:link]%></p>
    <% end %>
  </div>
</div>

app/views/welcome/show.html.erb
<div class="root-background">
  <div class="github-icon">
    <p class="gh-icon">MyGit<i class="fa fa-github fa-6" aria-hidden="true"></i>Place</p>
  </div>

  <% if current_user %>
    <div class="user-image">
      <p><%= image_tag(current_user.image, width: "100", height: "100") %></p>
    </div>
    <div class="col-md-4 user-texts">
      <p>Welcome, <%= current_user.screen_name %></p>
      <p>Name: <%= current_user.name %></p>
      <p> List of All Your Repos: <%= link_to "All Repos", repos_path %></p>
      <p> List of all Organizations: <%= link_to "All Organizations", organizations_path %></p>
      <p> Summary : <%= link_to "Feed from Users You Follow", events_path %> </p>
      <p> Your Recent Activity: <%= link_to "Commits", event_path(current_user)  %></p>
      <p> All Your Gists: <%= link_to "Gists", gists_path %>
      <p>Following: <%= current_user.following %></p>
      <p>Followers: <%= current_user.followers %></p>
      <p>Starred Repos: <%= @starred.count %></p>
    </div>
  <% end %>
</div>